name: "Build Sumo Logic App"
description: "Run the sumo CLI as a GitHub action"
inputs:
  output-file:
    description: "The file to write the build result to"
    required: true
    default: "build.json"
runs:
  using: "docker"
  image: "docker://ccaum/sumo-cli:latest"
  args:
    - app
    - build
    - -o
    - ${{ inputs.output-file }}
