name: "Build Sumo Logic App"
description: "Run the sumo CLI as a GitHub action"
inputs:
  stream:
    description: "The application stream to build. One of upstream, midstream, or downstream."
    required: true
    default: "downstream"
  output-file:
    description: "The file to write the build result to"
    required: true
    default: "build.json"
runs:
  using: "docker"
  image: "ccaum/sumo-cli"
  args:
    - "app"
    - "build"
    - ${{ inputs.stream }}
    - ${{ inputs.output-file }}
