name: "Push application build"
description: "Push an application build file to your Sumo Logic account"
inputs:
  file:
    description: "The path to the build file (json file) to push to your Sumo Logic account"
    required: true
    default: build.json
  access-id:
    description: "The Sumo Logic access ID"
    required: true
  access-key:
    description: "The Sumo Logic access key"
    required: true
  args:
    description: "Extra arguments to pass to the `sumo app push` command"
    required: false
  parent_folder_id:
    description: "The ID of the folder to install the application in"
    required: true
  deployment_region:
    description: "The region your Sumo Logic account is deployed in"
    required: true
    default: us1
runs:
  using: "docker"
  image: "docker://ccaum/sumo-cli:latest"
  env:
    SUMO_ACCESS_ID: ${{ inputs.access-id }}
    SUMO_ACCESS_KEY: ${{ inputs.access-key }}
    SUMO_DEPLOYMENT: ${{ inputs.deployment_region }}
  args:
    - "app"
    - "push"
    - ${{ inputs.args }}
    - ${{ inputs.file }}
